### PR TITLE
Create Three Questions to Ask When Hiring Software Developers

### PR DESCRIPTION
**Pull request by AmmarHub**

### CODE REVIEW

**Comment by AmmarHub** [comment]
@greentic @TomBradyWannabe What do you guys think of my 3 questions for hiring developers?

**Comment by TomBradyWannabe** [comment]
I'M HERE!

**Comment by AmmarHub** [comment]
@TomBradyWannabe Hey, thanks for the comments, I've updated my file, let me know what you think and :+1: if you're happy!

**Comment by greentic** [comment]
@AmmarHub Love the list!  Consider having them identify x that they use (e.g. version control system), identify competing alternatives, and explain why they choose to use x.

**Comment by TomBradyWannabe** [comment]
@greentic Good comments I agree. But it's already been +1'd! It's a go!
dancin'

**Comment by greentic** [comment]
@TomBradyWannabe I think we need two :+1: on each branch before committing, per the master file.

**Comment by AmmarHub** [comment]
@greentic Thanks, updated per your comment, please give me a thumbs up now!

**Comment by TomBradyWannabe** [comment]
:+1: :+1:  There ya go! There's two!

**Comment by greentic** [comment]
:+1: Nice work!

**Pull request merged**
