### PR TITLE
Create how-to-motivate-developers

### PR DESCRIPTION
**Pull request by TomBradyWannabe**
Motivation is important when dealing with humans!

### CODE REVIEW

**Comment by TomBradyWannabe** [comment]
@AmmarHub @greentic I hope you agree with my file. Lemme know what you guys think!

**Comment by AmmarHub** [comment]
@TomBradyWannabe Sorry typo, I meant *new languages and technologies...

**Comment by TomBradyWannabe** [comment]
@AmmarHub Thanks for the tip buddy! Fixed it and I think it's a lot better now

**Comment by TomBradyWannabe** [comment]
![Just feel like dancing] (http://www.pbh2.com/wordpress/wp-content/uploads/2013/06/funny-gif-kid-dancing.gif.webm)

**Comment by greentic** [comment]
@TomBradyWannabe Great list!  I would also consider adding a note from The Pragmatic Programmer -- fix broken windows, maintaining a culture of high quality by continuously fixing small problems will help keep the team motivated and engaged.

**Comment by TomBradyWannabe** [comment]
@greentic Good idea! I added a line about fixing the little things - thanks!
cats

**Comment by greentic** [comment]
:+1: :smiley_cat:

**Pull request merged**
